apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: writer-container
      image: busybox
      command: ["sh", "-c", "echo 'Hello, World!' > /shared-data/hello.txt; sleep 3600"]
      volumeMounts:
      - name: shared-volume
        mountPath: /shared-data  # Mount path inside this container
    - name: reader-container
      image: busybox
      command: ["sh", "-c", "cat /shared-data/hello.txt; sleep 3600"]
      volumeMounts:
      - name: shared-volume
        mountPath: /shared-data  # Mount path inside this container
  volumes:
  - name: shared-volume
    emptyDir: {}  # This defines an emptyDir volume, which is ephemeral
