apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-volume-example
spec:
  containers:
    - name: my-container
      image: nginx  # You can use any image; here we use nginx as an example
      volumeMounts:
        - mountPath: /usr/share/nginx/html  # Path inside the container where the volume will be mounted
          name: my-ephemeral-storage  # Name of the volume defined below
  volumes:
    - name: my-ephemeral-storage
      emptyDir: {}  # This defines an emptyDir volume, which is ephemeral
