apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx  # Example image; use the appropriate image for your application
    volumeMounts:
    - mountPath: /usr/share/nginx/html  # Path where the volume will be mounted inside the container
      name: my-storage  # This should match the volume name defined below
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: my-pvc  # Reference to your PVC
