apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
    - port: 80          # Port exposed by the service
      targetPort: 80    # Port on the Pod that the traffic will be forwarded to
