apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:latest
      command: ["sleep", "infinity"]  # Keeps the container running
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
